#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef PUSHFEATURESDK_SWIFT_H
#define PUSHFEATURESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import SFMCSDK;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PushFeatureSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class SFMCSdkModuleLogger;
@protocol SFMCSdkModuleConfig;
@class SFMCSdkComponents;
@protocol SFPushFeatureApi;
@class SFMCSdkMessage;
/// The main API class of PushFeature module
SWIFT_CLASS_NAMED("PushFeature")
@interface SFPushFeature : NSObject <SFMCModule, Subscriber>
/// Enum to get the Module Name
/// :nodoc:
@property (nonatomic) enum SFMCSdkModuleName name;
/// String to get the Module Version
/// :nodoc:
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull moduleVersion;)
+ (NSString * _Nonnull)moduleVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setModuleVersion:(NSString * _Nonnull)value;
/// Dictionary to get the SDK properties
/// :nodoc:
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nullable stateProperties;)
+ (NSDictionary<NSString *, NSString *> * _Nullable)stateProperties SWIFT_WARN_UNUSED_RESULT;
+ (void)setStateProperties:(NSDictionary<NSString *, NSString *> * _Nullable)newValue;
/// Unified Logger initialized for ‘Push Feature’ Module
/// Usage: logger.d(category: .event, message: “Message”)
/// Category : Enum with following values => auth, behavior, encryption, eventBus, network, module, sdk, storage, consent, coredata, database, event, identity, interface, location, session, util
/// :nodoc:
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkModuleLogger * _Nonnull logger;)
+ (SFMCSdkModuleLogger * _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
/// Initialize PushFeatureModule and return Shared instance
/// <ul>
///   <li>
///     Returns    SFMCModule PushFeatureModule
///     :nodoc:
///   </li>
/// </ul>
/// \param config Module config with module name and appid
///
/// \param components EncryptionManager, StorageManager, BehaviourManager
///
+ (id <SFMCModule> _Nullable)initModuleWithConfig:(id <SFMCSdkModuleConfig> _Nonnull)config components:(SFMCSdkComponents * _Nonnull)components SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Requests the Push Feature Module when it’s operational and safe to use. The provided callback will be invoked with the Push Feature Module when it’s ready.
/// All push feature module-related API calls should be made within this function.
/// \param callback A callback that will receive the Push Feature Module when it’s operational/ready.
///
+ (void)requestSdk:(void (^ _Nonnull)(id <SFPushFeatureApi> _Nullable))callback;
/// This method is used to receive message from publishers and handle push click event from MAM or MCE
/// \param message SFMCEvent, publish to specific Custom event
/// :nodoc:
///
- (void)receiveWithMessage:(SFMCSdkMessage * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFPushFeature (SWIFT_EXTENSION(PushFeatureSDK))
/// :nodoc:
+ (void)tearDownModule;
@end

@protocol SFMCSdkModuleIdentity;
@interface SFPushFeature (SWIFT_EXTENSION(PushFeatureSDK)) <PushFeatureProtocol>
/// This method is used to get the SDK identity attributes such as applicationId.
/// :nodoc:
- (id <SFMCSdkModuleIdentity> _Nullable)getIdentity SWIFT_WARN_UNUSED_RESULT;
/// This method properly closes down the PushFeatureModule. It should be used in any cases where references to the PushFeatureModule need to be released. Since this push feature module can be called
/// seperately without SFMCSDK. It should release itself when SFMCSDK is reinitialised.
/// :nodoc:
- (void)internalTearDown;
@end

@class NSData;
@class UNNotificationResponse;
@protocol SFMCSdkURLHandlingDelegate;
/// :nodoc:
SWIFT_PROTOCOL_NAMED("PushFeatureApi")
@protocol SFPushFeatureApi
- (void)setDeviceToken:(NSData * _Nonnull)deviceToken;
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT;
- (void)setPushEnabledWithPushEnabled:(BOOL)pushEnabled;
- (BOOL)isPushEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationResponse:(UNNotificationResponse * _Nonnull)response;
- (UNNotificationResponse * _Nullable)notificationResponse SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationUserInfo:(NSDictionary * _Nonnull)userInfo;
- (NSDictionary * _Nonnull)notificationUserInfo SWIFT_WARN_UNUSED_RESULT;
- (void)setURLHandlingDelegate:(id <SFMCSdkURLHandlingDelegate> _Nonnull)delegate;
@end

@interface SFPushFeature (SWIFT_EXTENSION(PushFeatureSDK)) <SFPushFeatureApi>
/// Responsible for sending the Apple device token back to all the subscribers. It marks the end of the token registration flow. If it is unable to reach Salesforce server, it will save the token and try again later.
/// This method is necessary to the implementation of Salesforce Push.
/// \param deviceToken Device token received from the customer application.
///
- (void)setDeviceToken:(NSData * _Nonnull)deviceToken;
/// Returns the device token as a String.
/// <ul>
///   <li>
///     Returns the device token as a String.
///   </li>
/// </ul>
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT;
/// Developer override to set the state of push enablement to true/false. If set to false, the application will not receive any push notifications once the Marketing Cloud server has been updated.
/// When this value is false, it takes precedence (overrides) the user notifications settings (i.e., setting this to false will always disable push.)
/// Conversely, if the user has notifications settings disabled, the developer cannot enable push via this method. A false value from either source (user settings or developer interface) always wins.
/// \param pushEnabled Set to true to enable push notifications.
///
- (void)setPushEnabledWithPushEnabled:(BOOL)pushEnabled;
/// Combination of push enabled from user notifications settings and push enabled by sdk.
/// <ul>
///   <li>
///     Returns BOOL value of the sdk’s push enablement override.
///   </li>
///   <li>
///     Returns BOOL value of the current user notifications settings state.
///   </li>
/// </ul>
- (BOOL)isPushEnabled SWIFT_WARN_UNUSED_RESULT;
/// Informs the module of the current notification response when user clicks a notification.
/// <ul>
///   <li>
///     Returns response: The UNNotificationResponse of the delivered notification.
///   </li>
/// </ul>
- (void)setNotificationResponse:(UNNotificationResponse * _Nonnull)response;
/// Returns the last notification response delivered to the module.
/// <ul>
///   <li>
///     Returns UNNotificationResponse: The last delivered notification’s UNNotificationResponse.
///   </li>
/// </ul>
- (UNNotificationResponse * _Nullable)notificationResponse SWIFT_WARN_UNUSED_RESULT;
/// Informs the module of the current userInfo when user clicks a notification.
/// \param userInfo The user info the current notification clicked to the module.
///
- (void)setNotificationUserInfo:(NSDictionary * _Nonnull)userInfo;
/// Returns the user info of the last notification delivered to the module.
/// <ul>
///   <li>
///     Returns Dictionary: The user info the last notification delivered to the module.
///   </li>
/// </ul>
- (NSDictionary * _Nonnull)notificationUserInfo SWIFT_WARN_UNUSED_RESULT;
/// Set URLHandling delegate to handle URLs in OpenDirect URLs, CloudPage URLs, CloudPage URLs from inbox messages
/// \param delegate set the delegate to handle URLs
///
- (void)setURLHandlingDelegate:(id <SFMCSdkURLHandlingDelegate> _Nonnull)delegate;
@end

/// This class  is used to set the configuration neded for Push Feature
/// :nodoc:
SWIFT_CLASS_NAMED("PushFeatureConfig")
@interface SFPushFeatureConfig : NSObject <SFMCSdkModuleConfig>
/// Enable or disable screen tracking
@property (nonatomic, readonly) BOOL trackScreens;
/// name of the module
@property (nonatomic, readonly) enum SFMCSdkModuleName name;
/// applicationId to initialize the SDK
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// PushFeatureConfigBuilder class
SWIFT_CLASS_NAMED("PushFeatureConfigBuilder")
@interface SFPushFeatureConfigBuilder : NSObject
/// Creates a PushFeatureConfig containing the current builder configuration settings. This can be passed to the ConfigBuilder  method(s)
/// <ul>
///   <li>
///     Returns PushFeatureConfig containing the current builder configuration settings.
///   </li>
/// </ul>
- (SFPushFeatureConfig * _Nonnull)build;
/// Sets the configuration value which allows sdk to control application badge count
/// <ul>
///   <li>
///     Returns the PushFeatureConfigBuilder instancetype value
///   </li>
/// </ul>
/// \param enabled Enables or disables application badge controlling
///
- (SFPushFeatureConfigBuilder * _Nonnull)setApplicationControlsBadging:(BOOL)enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
